POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Vídeo de teste",
  "description": "Teste da API local",
  "duration": 180
}

###

GET http://localhost:3333/videos?search=node


###
PUT http://localhost:3333/videos/2285af99-a8ab-45a3-bcdc-431d1b184bfd
Content-Type: application/json



{
  "title": "FLA X VAS",
  "description": "ODD de 5.6 = FLA",
  "duration": 1020
}

###

DELETE http://localhost:3333/videos/f4089565-5971-4552-b082-9737a2ddbc3b
